name: day06

on:
  workflow_dispatch:
  push:
    paths:
      - "day06"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        working-directory: ./day06
        run: cargo build --release --verbose
      - name: Run
        working-directory: ./day06
        run: time target/release/day06 < input/input.txt
