name: day03

on:
  workflow_dispatch:
  push:
    paths:
      - "day03"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        working-directory: ./day03
        run: cargo build --release --verbose
      - name: Run
        working-directory: ./day03
        run: time target/release/day03 < input/input.txt
