name: day07

on:
  workflow_dispatch:
  push:
    paths:
      - "day07"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        working-directory: ./day07
        run: cargo build --release --verbose
      - name: Run
        working-directory: ./day07
        run: time target/release/advent-of-code-2022 < input/input.txt
